package tunnel

import (
	"sync"

	"github.com/gorilla/websocket"
)

// Session holds the CLI's tunnel WebSocket connection and a done channel.
// done is closed by ProxyHandler when the browser session ends —
// this signals RegisterHandler to unblock and clean up the HTTP connection.
type Session struct {
	Conn *websocket.Conn
	done chan struct{}
}

// Registry is an in-memory map of sessionId → CLI tunnel connection.
// It is initialised once in server startup and passed to handlers.
// Do NOT use global variables — pass the registry as a parameter.
//
// Rules (from ARCHITECTURE.md):
//   - In-memory only. No persistence. Server restart drops all sessions.
//   - Session IDs are generated by the CLI, not the server.
//   - RWMutex: read lock for Get, write lock for Register/Remove.
type Registry struct {
	mu       sync.RWMutex
	sessions map[string]*Session
}

// NewRegistry returns an initialised, empty Registry.
func NewRegistry() *Registry {
	return &Registry{
		sessions: make(map[string]*Session),
	}
}

// Register stores the CLI's tunnel WebSocket under sessionId and returns
// the Session. The caller (RegisterHandler) waits on Session.Wait()
// until ProxyHandler signals the session is over.
func (r *Registry) Register(sessionID string, conn *websocket.Conn) *Session {
	s := &Session{
		Conn: conn,
		done: make(chan struct{}),
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	r.sessions[sessionID] = s
	return s
}

// Get returns the Session for sessionId, or false if not found.
func (r *Registry) Get(sessionID string) (*Session, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	s, ok := r.sessions[sessionID]
	return s, ok
}

// Remove deletes the session from the registry.
func (r *Registry) Remove(sessionID string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	delete(r.sessions, sessionID)
}

// Wait blocks until ProxyHandler closes the session (browser disconnects).
// Called by RegisterHandler to keep the CLI's HTTP connection alive.
func (s *Session) Wait() {
	<-s.done
}

// close signals RegisterHandler that the session is over.
// Only called by ProxyHandler's sync.Once cleanup.
func (s *Session) close() {
	close(s.done)
}